
[project]
name = "model-catalog"
version = "0.1.0"
description = "Model Catalog service (SMR + DynamoDB) for ai-microgen"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "pydantic>=2.0",
  "boto3",
]
