
version: "3.9"

# In this half-step, we stand up only infrastructure dependencies used by multiple microservices.
# Services themselves (webapi, orchestrator, etc.) arrive in the next patches.

services:
  redis:
    image: redis:7
    container_name: ai-microgen-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 20

  minio:
    image: quay.io/minio/minio
    container_name: ai-microgen-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO console
    volumes:
      - minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  minio: {}
