
[project]
name = "webapi"
version = "0.2.0"
description = "Edge Web/API for ai-microgen"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "httpx",
  "boto3",
  "pydantic>=2.0",
]
