
[project]
name = "notify-service"
version = "0.1.0"
description = "Real-time notifications via SSE/WebSocket backed by Redis pubsub"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "redis",
]
