
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-worker
  namespace: ai-microgen
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-worker
  minReplicas: 1
  maxReplicas: 15
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 45
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: External
      external:
        metric:
          name: fair_queue_depth_total
          selector:
            matchLabels:
              type: video
        target:
          type: AverageValue
          averageValue: "1"   # target ~1 queued video per pod
