
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-config
  namespace: ai-microgen
data:
  REDIS_URL: redis://redis:6379/0
  S3_ENDPOINT: http://minio:9000
  S3_REGION: us-east-1
  S3_ACCESS_KEY: minioadmin
  S3_SECRET_KEY: minioadmin
  ARTIFACTS_BUCKET: artifacts
  MODELS_BUCKET: models
  PROMPT_SERVICE_URL: http://prompt-service:8082
  NOTIFY_SERVICE_URL: http://notify-service:8083
