
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-worker
  namespace: ai-microgen
spec:
  replicas: 2
  selector: {matchLabels: {app: gpu-worker}}
  template:
    metadata: {labels: {app: gpu-worker}}
    spec:
      containers:
        - name: gpu-worker
          image: gpu-worker:latest
          ports: [{containerPort: 8090}]
          env:
            - {name: ARTIFACTS_ROOT, value: "/data/artifacts"}
            - {name: S3_UPLOAD, value: "0"}
          volumeMounts: [{name: data, mountPath: /data}]
      volumes: [{name: data, emptyDir: {}}]
---
apiVersion: v1
kind: Service
metadata:
  name: gpu-worker
  namespace: ai-microgen
spec:
  selector: {app: gpu-worker}
  ports: [{port: 8090, targetPort: 8090}]
