
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-microgen
resources:
  - ../../base/video-worker
patches:
  - path: patch-sa-annotations.yaml
  - path: patch-gpu-node.yaml
